/* 服装目录：与原版 v6.4.0 商城完全一致的 72 套 + 经典原装。生成自原版 manifest，勿手改。 */

export interface OutfitDef {
  id: string;
  name: string;
  category: string;
  kind: 'suit' | 'dress';
  price: number;
  color: string;
  description: string;
}

export const OUTFITS: OutfitDef[] = [
  { id: 'classic', name: '经典奶蛙', category: '原装', kind: 'suit', price: 0, color: '#f9cc2b', description: '原版奶蛙 · 奶油肚皮与圆圆眼睛' },
  { id: 'suit', name: '午夜绅士', category: '西装', kind: 'suit', price: 280, color: '#334b76', description: '西装 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'jk', name: '莓果学院', category: 'JK', kind: 'dress', price: 220, color: '#eecb97', description: 'JK · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'lolita', name: '紫糖茶会', category: 'Lolita', kind: 'dress', price: 460, color: '#ae80da', description: 'Lolita · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'uniform', name: '晴空校队', category: '校服', kind: 'suit', price: 180, color: '#659edf', description: '校服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'dress', name: '花间漫步', category: '连衣裙', kind: 'dress', price: 360, color: '#eccd83', description: '连衣裙 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'sailor', name: '海盐水手', category: '水手服', kind: 'dress', price: 260, color: '#eecb97', description: '水手服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'wizard', name: '星夜魔法师', category: '法师', kind: 'dress', price: 520, color: '#7871ba', description: '法师 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'astronaut', name: '月球旅行家', category: '宇航服', kind: 'suit', price: 780, color: '#a8dbe5', description: '宇航服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'detective', name: '焦糖侦探', category: '风衣', kind: 'suit', price: 420, color: '#ce9569', description: '风衣 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'chef', name: '奶油主厨', category: '厨师服', kind: 'suit', price: 340, color: '#eecb97', description: '厨师服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'racer', name: '极速红线', category: '赛车服', kind: 'suit', price: 600, color: '#e87565', description: '赛车服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'pirate', name: '宝藏船长', category: '海盗装', kind: 'suit', price: 680, color: '#334b76', description: '海盗装 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'hanfu', name: '竹月清风', category: '汉服', kind: 'dress', price: 560, color: '#64c9ac', description: '汉服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'kimono', name: '樱町花见', category: '和服', kind: 'dress', price: 580, color: '#eda9cb', description: '和服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'flamenco', name: '绯红舞会', category: '舞裙', kind: 'dress', price: 620, color: '#c94b65', description: '舞裙 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'explorer', name: '沙海探险家', category: '探险装', kind: 'suit', price: 480, color: '#ce9569', description: '探险装 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'winter', name: '峡湾暖冬', category: '冬装', kind: 'suit', price: 540, color: '#68bdd7', description: '冬装 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'street', name: '薄荷街头', category: '卫衣', kind: 'suit', price: 380, color: '#64c9ac', description: '卫衣 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'coronation', name: '加冕之夜', category: '礼服', kind: 'suit', price: 300, color: '#334b76', description: '礼服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'princess', name: '星屑公主', category: '礼服', kind: 'dress', price: 345, color: '#eda9cb', description: '礼服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'knight', name: '银月骑士', category: '幻想', kind: 'suit', price: 390, color: '#a8dbe5', description: '幻想 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'bard', name: '森林吟游者', category: '幻想', kind: 'suit', price: 435, color: '#64c9ac', description: '幻想 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'fairy', name: '花园精灵', category: '幻想', kind: 'dress', price: 480, color: '#64c9ac', description: '幻想 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'angel', name: '云端信使', category: '幻想', kind: 'suit', price: 525, color: '#eecb97', description: '幻想 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'dragon', name: '龙焰守卫', category: '幻想', kind: 'suit', price: 570, color: '#c94b65', description: '幻想 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'witch', name: '南瓜女巫', category: '幻想', kind: 'dress', price: 615, color: '#ae80da', description: '幻想 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'mermaid', name: '珊瑚海歌', category: '幻想', kind: 'dress', price: 660, color: '#68bdd7', description: '幻想 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'cosmonaut', name: '流星探索者', category: '职业', kind: 'suit', price: 705, color: '#a8dbe5', description: '职业 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'robot', name: '霓虹机甲', category: '幻想', kind: 'suit', price: 750, color: '#5e94c6', description: '幻想 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'pilot', name: '蓝天飞行员', category: '职业', kind: 'suit', price: 795, color: '#ce9569', description: '职业 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'firefighter', name: '消防勇士', category: '职业', kind: 'suit', price: 300, color: '#ddad54', description: '职业 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'medic', name: '薄荷医生', category: '职业', kind: 'suit', price: 345, color: '#eecb97', description: '职业 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'nurse', name: '暖心护理', category: '职业', kind: 'dress', price: 390, color: '#eda9cb', description: '职业 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'builder', name: '工地队长', category: '职业', kind: 'suit', price: 435, color: '#659edf', description: '职业 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'officer', name: '星蓝巡逻', category: '职业', kind: 'suit', price: 480, color: '#334b76', description: '职业 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'postman', name: '信件旅行家', category: '职业', kind: 'suit', price: 525, color: '#64c9ac', description: '职业 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'gardener', name: '花园管家', category: '职业', kind: 'suit', price: 570, color: '#659edf', description: '职业 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'baker', name: '草莓烘焙师', category: '职业', kind: 'suit', price: 615, color: '#eda9cb', description: '职业 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'barista', name: '咖啡店长', category: '职业', kind: 'suit', price: 660, color: '#ce9569', description: '职业 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'scientist', name: '泡泡研究员', category: '职业', kind: 'suit', price: 705, color: '#eecb97', description: '职业 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'artist', name: '彩虹画家', category: '职业', kind: 'suit', price: 750, color: '#eecb97', description: '职业 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'musician', name: '爵士音符', category: '礼服', kind: 'suit', price: 795, color: '#c94b65', description: '礼服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'conductor', name: '燕尾指挥家', category: '礼服', kind: 'suit', price: 300, color: '#52516c', description: '礼服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'executive', name: '玫金领航', category: '礼服', kind: 'suit', price: 345, color: '#ae80da', description: '礼服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'wedding', name: '云纱婚礼', category: '礼服', kind: 'dress', price: 390, color: '#eecb97', description: '礼服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'gothic', name: '黑曜蔷薇', category: '礼服', kind: 'dress', price: 435, color: '#52516c', description: '礼服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'ballet', name: '桃粉芭蕾', category: '礼服', kind: 'dress', price: 480, color: '#eda9cb', description: '礼服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'dancer', name: '海风舞者', category: '礼服', kind: 'dress', price: 525, color: '#68bdd7', description: '礼服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'disco', name: '星光舞池', category: '礼服', kind: 'suit', price: 570, color: '#ae80da', description: '礼服 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'punk', name: '朋克旋律', category: '街头', kind: 'suit', price: 615, color: '#52516c', description: '街头 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'hiphop', name: '霓虹节拍', category: '街头', kind: 'suit', price: 660, color: '#ae80da', description: '街头 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'skater', name: '城市滑手', category: '街头', kind: 'suit', price: 705, color: '#659edf', description: '街头 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'basketball', name: '落日球场', category: '运动', kind: 'suit', price: 750, color: '#e87565', description: '运动 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'football', name: '绿茵冲刺', category: '运动', kind: 'suit', price: 795, color: '#64c9ac', description: '运动 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'tennis', name: '草莓网球', category: '运动', kind: 'dress', price: 300, color: '#eecb97', description: '运动 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'baseball', name: '蓝白棒球', category: '运动', kind: 'suit', price: 345, color: '#eecb97', description: '运动 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'holiday', name: '海岛假日', category: '旅行', kind: 'suit', price: 390, color: '#eccd83', description: '旅行 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'diver', name: '深海潜行', category: '运动', kind: 'suit', price: 435, color: '#52516c', description: '运动 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'skier', name: '雪原疾驰', category: '运动', kind: 'suit', price: 480, color: '#c94b65', description: '运动 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'climber', name: '峭壁攀登', category: '旅行', kind: 'suit', price: 525, color: '#e87565', description: '旅行 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'hiker', name: '松林徒步', category: '旅行', kind: 'suit', price: 570, color: '#64c9ac', description: '旅行 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'camper', name: '营火星空', category: '旅行', kind: 'suit', price: 615, color: '#659edf', description: '旅行 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'fisher', name: '湖畔钓手', category: '旅行', kind: 'suit', price: 660, color: '#ce9569', description: '旅行 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'cowboy', name: '荒野牛仔', category: '旅行', kind: 'suit', price: 705, color: '#659edf', description: '旅行 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'sheriff', name: '沙漠警长', category: '旅行', kind: 'suit', price: 750, color: '#ce9569', description: '旅行 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'samurai', name: '樱刃剑客', category: '幻想', kind: 'suit', price: 795, color: '#334b76', description: '幻想 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'ninja', name: '月影疾行', category: '幻想', kind: 'suit', price: 300, color: '#52516c', description: '幻想 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'panda', name: '竹林熊猫', category: '玩偶', kind: 'suit', price: 345, color: '#eecb97', description: '玩偶 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'bee', name: '蜂蜜派对', category: '玩偶', kind: 'suit', price: 390, color: '#ddad54', description: '玩偶 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'bunny', name: '糖果兔兔', category: '玩偶', kind: 'suit', price: 435, color: '#eda9cb', description: '玩偶 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'bear', name: '焦糖小熊', category: '玩偶', kind: 'suit', price: 480, color: '#ce9569', description: '玩偶 · 适配奶蛙模型 · 可旋转和动态试穿' },
  { id: 'dinosaur', name: '薄荷恐龙', category: '玩偶', kind: 'suit', price: 525, color: '#64c9ac', description: '玩偶 · 适配奶蛙模型 · 可旋转和动态试穿' },
];
